import type { Metadata } from "next";
import { Space_Grotesk } from "next/font/google";
import "../styles/globals.css";
import Header from "@/components/Shared/Header/Header";
import Footer from "@/components/Shared/Footer/Footer";

const SpaceGrotesk = Space_Grotesk({
  variable: "--font-space-grotesk", // ✅ match your CSS
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "GoEvent",
  description: "Generated by Flixza Global",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${SpaceGrotesk.variable} antialiased`}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
